language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pylint src --rcfile=pylint_settings.rc > CI_test_results/${TRAVIS_BUILD_NUMBER}_pylint_results.txt
  - pytest > CI_test_results/${TRAVIS_BUILD_NUMBER}_pytest_results.txt
notifications:
  email:
    - afa2132@columbia.edu
    - kjp2157@columbia.edu
    - tio2001@columbia.edu
    - mak2265@columbia.edu