language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pylint src --rcfile=pylint_settings.rc 2>&1 | tee pylint_out.txt
  - pytest 2>&1 | tee pylint_out.txt
  - git commit -a -m "Upload CI output"
  - git push
notifications:
  email:
    - afa2132@columbia.edu
    - kjp2157@columbia.edu
    - tio2001@columbia.edu
    - mak2265@columbia.edu