language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - touch travis_ci_output/${TRAVIS_BUILD_NUMBER}_pylint_out.txt
  - touch travis_ci_output/${TRAVIS_BUILD_NUMBER}_pytest_out.txt
  - chmod u+w travis_ci_output/${TRAVIS_BUILD_NUMBER}_pylint_out.txt
  - chmod u+w travis_ci_output/${TRAVIS_BUILD_NUMBER}_pytest_out.txt
  - pylint src --rcfile=pylint_settings.rc 2>&1 | tee travis_ci_output/${TRAVIS_BUILD_NUMBER}_pylint_out.txt
  - pytest 2>&1 | travis_ci_output/${TRAVIS_BUILD_NUMBER}_pytest_out.txt
notifications:
  email:
    - afa2132@columbia.edu
    - kjp2157@columbia.edu
    - tio2001@columbia.edu
    - mak2265@columbia.edu