language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
notifications:
  email:
    - afa2132@columbia.edu
    - kjp2157@columbia.edu
    - tio2001@columbia.edu
    - mak2265@columbia.edu
script:
  - bash travis-tests.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: travis_ci_output
  target-branch: travis_ci_output
  on:
    branch: master